/**
 * Maps nationality strings (as returned by football-data.org) to ISO 3166-1 alpha-2
 * country codes used by flagcdn.com. Sub-national flags (England, Scotland, Wales)
 * use the flagcdn.com sub-division codes.
 */
const NATIONALITY_CODES: Record<string, string> = {
  // Europe
  "France": "fr",
  "Germany": "de",
  "Spain": "es",
  "England": "gb-eng",
  "Portugal": "pt",
  "Netherlands": "nl",
  "Belgium": "be",
  "Italy": "it",
  "Croatia": "hr",
  "Switzerland": "ch",
  "Denmark": "dk",
  "Poland": "pl",
  "Austria": "at",
  "Serbia": "rs",
  "Czechia": "cz",
  "Czech Republic": "cz",
  "Scotland": "gb-sct",
  "Ukraine": "ua",
  "Turkey": "tr",
  "Türkiye": "tr",
  "Hungary": "hu",
  "Albania": "al",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Romania": "ro",
  "Greece": "gr",
  "Norway": "no",
  "Sweden": "se",
  "Finland": "fi",
  "Iceland": "is",
  "Ireland": "ie",
  "Republic of Ireland": "ie",
  "Wales": "gb-wls",
  "Northern Ireland": "gb-nir",
  "Bosnia and Herzegovina": "ba",
  "Bosnia & Herzegovina": "ba",
  "Bosnia-Herzegovina": "ba",
  "Kosovo": "xk",
  "North Macedonia": "mk",
  "Montenegro": "me",
  "Georgia": "ge",
  "Armenia": "am",
  "Azerbaijan": "az",
  "Kazakhstan": "kz",
  "Belarus": "by",
  "Moldova": "md",
  "Bulgaria": "bg",
  "Luxembourg": "lu",
  "Cyprus": "cy",
  "Malta": "mt",
  "Estonia": "ee",
  "Latvia": "lv",
  "Lithuania": "lt",
  "Russia": "ru",
  "Andorra": "ad",
  "San Marino": "sm",
  "Faroe Islands": "fo",
  "Gibraltar": "gi",
  "Liechtenstein": "li",
  "Israel": "il",

  // South America
  "Brazil": "br",
  "Argentina": "ar",
  "Colombia": "co",
  "Uruguay": "uy",
  "Ecuador": "ec",
  "Venezuela": "ve",
  "Chile": "cl",
  "Bolivia": "bo",
  "Paraguay": "py",
  "Peru": "pe",
  "Suriname": "sr",
  "Guyana": "gy",

  // North & Central America + Caribbean
  "United States": "us",
  "USA": "us",
  "Mexico": "mx",
  "Canada": "ca",
  "Costa Rica": "cr",
  "Jamaica": "jm",
  "Honduras": "hn",
  "Panama": "pa",
  "Trinidad and Tobago": "tt",
  "Trinidad & Tobago": "tt",
  "Cuba": "cu",
  "Haiti": "ht",
  "Guatemala": "gt",
  "El Salvador": "sv",
  "Nicaragua": "ni",
  "Belize": "bz",
  "Dominican Republic": "do",
  "Barbados": "bb",
  "Curacao": "cw",
  "Curaçao": "cw",

  // Africa
  "Morocco": "ma",
  "Senegal": "sn",
  "Nigeria": "ng",
  "Cameroon": "cm",
  "Egypt": "eg",
  "Ghana": "gh",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  "South Africa": "za",
  "Tunisia": "tn",
  "Algeria": "dz",
  "Mali": "ml",
  "Cape Verde": "cv",
  "Guinea": "gn",
  "Mozambique": "mz",
  "Angola": "ao",
  "DR Congo": "cd",
  "Congo DR": "cd",
  "Democratic Republic of the Congo": "cd",
  "Congo": "cg",
  "Tanzania": "tz",
  "Rwanda": "rw",
  "Namibia": "na",
  "Benin": "bj",
  "Comoros": "km",
  "Gabon": "ga",
  "Mauritania": "mr",
  "Zimbabwe": "zw",
  "Zambia": "zm",
  "Uganda": "ug",
  "Ethiopia": "et",
  "Kenya": "ke",
  "Libya": "ly",
  "Sudan": "sd",
  "Liberia": "lr",
  "Sierra Leone": "sl",
  "Gambia": "gm",
  "Burkina Faso": "bf",
  "Togo": "tg",
  "Guinea-Bissau": "gw",
  "Equatorial Guinea": "gq",

  // Asia
  "Japan": "jp",
  "South Korea": "kr",
  "Saudi Arabia": "sa",
  "Iran": "ir",
  "Australia": "au",
  "Qatar": "qa",
  "Iraq": "iq",
  "Indonesia": "id",
  "Jordan": "jo",
  "Uzbekistan": "uz",
  "Kyrgyzstan": "kg",
  "Tajikistan": "tj",
  "Turkmenistan": "tm",
  "Lebanon": "lb",
  "Syria": "sy",
  "Bahrain": "bh",
  "Kuwait": "kw",
  "Oman": "om",
  "Yemen": "ye",
  "United Arab Emirates": "ae",
  "Palestine": "ps",
  "India": "in",
  "Thailand": "th",
  "Vietnam": "vn",
  "China": "cn",
  "Philippines": "ph",
  "Malaysia": "my",
  "Singapore": "sg",
  "North Korea": "kp",
  "Mongolia": "mn",
  "Pakistan": "pk",
  "Bangladesh": "bd",
  "Afghanistan": "af",

  // Oceania
  "New Zealand": "nz",
  "Papua New Guinea": "pg",
  "Fiji": "fj",
  "Solomon Islands": "sb",
  "Vanuatu": "vu",
  "Samoa": "ws",
  "Tonga": "to",
};

/**
 * Returns the ISO code for use with flagcdn.com, or null if unknown.
 */
export function getNationalityCode(nationality: string): string | null {
  return NATIONALITY_CODES[nationality] ?? null;
}

/**
 * Returns a flagcdn.com URL for the given nationality.
 * Falls back to null if the nationality is not mapped.
 */
export function getFlagUrl(nationality: string, width: 20 | 40 | 80 = 20): string | null {
  const code = getNationalityCode(nationality);
  if (!code) return null;
  return `https://flagcdn.com/w${width}/${code}.png`;
}
