/**
 * Maps nationality strings (as returned by football-data.org) to flag emojis.
 * Covers all likely World Cup 2026 squads plus common nationality variations.
 */
const NATIONALITY_FLAGS: Record<string, string> = {
  // Europe
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Spain": "🇪🇸",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Portugal": "🇵🇹",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Italy": "🇮🇹",
  "Croatia": "🇭🇷",
  "Switzerland": "🇨🇭",
  "Denmark": "🇩🇰",
  "Poland": "🇵🇱",
  "Austria": "🇦🇹",
  "Serbia": "🇷🇸",
  "Czechia": "🇨🇿",
  "Czech Republic": "🇨🇿",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Ukraine": "🇺🇦",
  "Turkey": "🇹🇷",
  "Türkiye": "🇹🇷",
  "Hungary": "🇭🇺",
  "Albania": "🇦🇱",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Romania": "🇷🇴",
  "Greece": "🇬🇷",
  "Norway": "🇳🇴",
  "Sweden": "🇸🇪",
  "Finland": "🇫🇮",
  "Iceland": "🇮🇸",
  "Ireland": "🇮🇪",
  "Republic of Ireland": "🇮🇪",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Northern Ireland": "🇬🇧",
  "Bosnia and Herzegovina": "🇧🇦",
  "Bosnia & Herzegovina": "🇧🇦",
  "Kosovo": "🇽🇰",
  "North Macedonia": "🇲🇰",
  "Montenegro": "🇲🇪",
  "Georgia": "🇬🇪",
  "Armenia": "🇦🇲",
  "Azerbaijan": "🇦🇿",
  "Kazakhstan": "🇰🇿",
  "Belarus": "🇧🇾",
  "Moldova": "🇲🇩",
  "Bulgaria": "🇧🇬",
  "Luxembourg": "🇱🇺",
  "Cyprus": "🇨🇾",
  "Malta": "🇲🇹",
  "Estonia": "🇪🇪",
  "Latvia": "🇱🇻",
  "Lithuania": "🇱🇹",
  "Russia": "🇷🇺",
  "Andorra": "🇦🇩",
  "San Marino": "🇸🇲",
  "Faroe Islands": "🇫🇴",
  "Gibraltar": "🇬🇮",
  "Liechtenstein": "🇱🇮",
  "Israel": "🇮🇱",

  // South America
  "Brazil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Colombia": "🇨🇴",
  "Uruguay": "🇺🇾",
  "Ecuador": "🇪🇨",
  "Venezuela": "🇻🇪",
  "Chile": "🇨🇱",
  "Bolivia": "🇧🇴",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Suriname": "🇸🇷",
  "Guyana": "🇬🇾",

  // North & Central America + Caribbean
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Mexico": "🇲🇽",
  "Canada": "🇨🇦",
  "Costa Rica": "🇨🇷",
  "Jamaica": "🇯🇲",
  "Honduras": "🇭🇳",
  "Panama": "🇵🇦",
  "Trinidad and Tobago": "🇹🇹",
  "Trinidad & Tobago": "🇹🇹",
  "Cuba": "🇨🇺",
  "Haiti": "🇭🇹",
  "Guatemala": "🇬🇹",
  "El Salvador": "🇸🇻",
  "Nicaragua": "🇳🇮",
  "Belize": "🇧🇿",
  "Dominican Republic": "🇩🇴",
  "Barbados": "🇧🇧",
  "Grenada": "🇬🇩",
  "Curacao": "🇨🇼",
  "Curaçao": "🇨🇼",

  // Africa
  "Morocco": "🇲🇦",
  "Senegal": "🇸🇳",
  "Nigeria": "🇳🇬",
  "Cameroon": "🇨🇲",
  "Egypt": "🇪🇬",
  "Ghana": "🇬🇭",
  "Ivory Coast": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "South Africa": "🇿🇦",
  "Tunisia": "🇹🇳",
  "Algeria": "🇩🇿",
  "Mali": "🇲🇱",
  "Cape Verde": "🇨🇻",
  "Guinea": "🇬🇳",
  "Mozambique": "🇲🇿",
  "Angola": "🇦🇴",
  "DR Congo": "🇨🇩",
  "Congo DR": "🇨🇩",
  "Democratic Republic of the Congo": "🇨🇩",
  "Congo": "🇨🇬",
  "Tanzania": "🇹🇿",
  "Rwanda": "🇷🇼",
  "Namibia": "🇳🇦",
  "Benin": "🇧🇯",
  "Comoros": "🇰🇲",
  "Gabon": "🇬🇦",
  "Mauritania": "🇲🇷",
  "Zimbabwe": "🇿🇼",
  "Zambia": "🇿🇲",
  "Uganda": "🇺🇬",
  "Ethiopia": "🇪🇹",
  "Kenya": "🇰🇪",
  "Libya": "🇱🇾",
  "Sudan": "🇸🇩",
  "Liberia": "🇱🇷",
  "Sierra Leone": "🇸🇱",
  "Gambia": "🇬🇲",
  "Burkina Faso": "🇧🇫",
  "Togo": "🇹🇬",
  "Guinea-Bissau": "🇬🇼",
  "Equatorial Guinea": "🇬🇶",

  // Asia
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Saudi Arabia": "🇸🇦",
  "Iran": "🇮🇷",
  "Australia": "🇦🇺",
  "Qatar": "🇶🇦",
  "Iraq": "🇮🇶",
  "Indonesia": "🇮🇩",
  "Jordan": "🇯🇴",
  "Uzbekistan": "🇺🇿",
  "Kyrgyzstan": "🇰🇬",
  "Tajikistan": "🇹🇯",
  "Turkmenistan": "🇹🇲",
  "Lebanon": "🇱🇧",
  "Syria": "🇸🇾",
  "Bahrain": "🇧🇭",
  "Kuwait": "🇰🇼",
  "Oman": "🇴🇲",
  "Yemen": "🇾🇪",
  "United Arab Emirates": "🇦🇪",
  "Palestine": "🇵🇸",
  "India": "🇮🇳",
  "Thailand": "🇹🇭",
  "Vietnam": "🇻🇳",
  "China": "🇨🇳",
  "Philippines": "🇵🇭",
  "Malaysia": "🇲🇾",
  "Singapore": "🇸🇬",
  "North Korea": "🇰🇵",
  "Mongolia": "🇲🇳",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Afghanistan": "🇦🇫",

  // Oceania
  "New Zealand": "🇳🇿",
  "Papua New Guinea": "🇵🇬",
  "Fiji": "🇫🇯",
  "Solomon Islands": "🇸🇧",
  "Vanuatu": "🇻🇺",
  "Samoa": "🇼🇸",
  "Tonga": "🇹🇴",
  "Tahiti": "🇵🇫",
  "New Caledonia": "🇳🇨",
};

export function getFlagEmoji(nationality: string): string {
  return NATIONALITY_FLAGS[nationality] ?? "🌍";
}
